# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: networkpolicynginx
# spec:
#   podSelector:
#     matchLabels:
#       app: nginx
#   ingress:
#   - ports:
#     - port: 80
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-tondu-ingress
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx
    ports:
    - port: 443
      protocol: TCP
