apiVersion: v1
kind: Service
metadata:
  name: tinku-service
spec:
  selector:
    papa: pushpa
  ports:
  - port: 9000
    targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: tinku-service-clusterip
spec:
  selector:
    papa: pushpa
  ports:
  - port: 9000
    targetPort: 80
  type: ClusterIP