apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pv
spec:
  containers:
  - name: my-app
    image: nginx:latest
    ports:
    - containerPort: 80
    
    volumeMounts:
    - mountPath: /data
      name: my-storage

  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: honeymoon-photos

