apiVersion: v1
kind: PersistentVolume
metadata:
  name: pyaar-ka-storage
spec:
  accessModes: 
  - ReadWriteMany
  azureFile:
    secretName: shadikephotos-ka-creds
    shareName: test
  capacity: 
    storage: 1Gi
  storageClassName: azurefile-static

