apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: honeymoon-photos
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-static 
