apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: nginx
spec:
  containers:
  - name: myapp
    image: nginx:latest
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp1
  labels:
    app: nginx
spec:
  containers:
  - name: myapp
    image: nginx:latest
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp2
  labels:
    app: nginx
spec:
  containers:
  - name: myapp
    image: nginx:latest
    ports:
      - containerPort: 80
