apiVersion: v1
kind: Pod
metadata:
  name: myapp-sc
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

    volumeMounts:
    - mountPath: /data
      name: my-storage  

  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: mypvc      
